version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  # jobs:
  #   post_install:
  #     - sphinx-build -b linkcheck

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
