version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  build:
    post_checkout:
      - echo "export MYVAR1=myvar1" >> ~/.bash_profile
      - echo "export MYVAR2=myvar2" >> ~/.bash_profile
      - echo "export MYVAR3=myvar3" >> ~/.bash_profile
    post_build:
      - env

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
