version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "16"
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive docs/* $READTHEDOCS_OUTPUT/html/

    # This build just copy the ``readthedocs-build.yaml`` file,
    # but it could be generated dynamically by the doctool.
    # The generation of this file relies on the doctool itself.
    # This file is the contract between the doctool and Read the Docs.
    - cp docs/readthedocs-build.yaml $READTHEDOCS_OUTPUT/html/

    - cat $READTHEDOCS_OUTPUT/html/readthedocs-build.yaml
