version: 2

build:
  os: ubuntu-22.04
  tools:
    ruby: "3.3"
  commands:
    - gem install bundle
    - bundle install
    - jekyll build --destination $READTHEDOCS_OUTPUT/html --baseurl $(echo -n "$READTHEDOCS_CANONICAL_URL" | cut -d '/' -f 4-)
