version: 2

build:
  os: ubuntu-20.04
  jobs:
    pre_checkout:
      - echo pre_checkout
      - echo `date`
    post_checkout:
      - echo post_checkout
      - echo `date`
      # https://github.com/readthedocs/readthedocs.org/issues/8201#issuecomment-1018511443
      - git fetch --unshallow
    pre_system_dependencies:
      - echo pre_system_dependencies
      - echo `date`
    post_system_dependencies:
      - echo post_system_dependencies
      - echo `date`
    pre_create_environment:
      - echo pre_create_environment
      - echo `date`
    post_create_environment:
      - echo post_create_environment
      - echo `date`
    pre_install:
      - echo pre_install
      - echo `date`
    post_install:
      - echo post_install
      - echo `date`
    pre_build:
      - echo pre_build
      - echo `date`
      - sed **/*.rst -i -e "s|{VERSION}|${READTHEDOCS_VERSION_NAME}|g"
    post_build:
      - echo post_build
      - echo `date`
  tools:
    python: "3"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
