version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
    nodejs: "18"
    rust: "1.61"
    golang: "1.18"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
