version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
    - libmagic1  # python-magic
    - graphviz   # dot command
  jobs:
    post_build:
      - mkdir --parents _readthedocs/htmlzip _readthedocs/pdf
      - sphinx-build -b zundler docs/ _readthedocs/$READTHEDOCS_PROJECT
      - cd _readthedocs ; zip -r -j htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT
      - sphinx-build -M simplepdf docs/ _readthedocs/
      - mv _readthedocs/simplepdf/"Test Builds.pdf" _readthedocs/pdf/$READTHEDOCS_PROJECT.pdf

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
