version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_build:
      - mkdir --parents $READTHEDOCS_OUTPUT/pdf
      - wget https://www.sphinx-doc.org/_/downloads/en/master/pdf/ -O $READTHEDOCS_OUTPUT/pdf/sphinx.pdf

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt


formats: []
