version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - mkdir --parents _build/html/ _readthedocs/html/
    - echo "Hello world!" > _build/html/index.html
    - cp _build/html/index.html _readthedocs/html/
