version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install pipx
      - pip install pipx
      # Install poetry
      # https://python-poetry.org/docs/#installing-with-pipx
      - pipx install poetry
      # Install project's dependencies
      - pipx run poetry install

sphinx:
  configuration: docs/conf.py
