version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - pip install -r requirements.txt
    - jupyter-book create book/
    - jupyter-book build --all book/
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - mv book/_build/html/* $READTHEDOCS_OUTPUT/html/
