version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
  jobs:
    post_build:
      - sphinx-build -b rinoh docs/ _build/rinohtype/
      - mkdir _readthedocs/pdf
      - mv _build/rinohtype/test-builds.pdf _readthedocs/pdf

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
