version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
    - libasound2
  jobs:
    pre_build:
      - shot-scraper install
      - shot-scraper https://datasette.io/ --height 800 -o docs/_static/datasette.png

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
