version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # Run all the commands manually to avoid installing pre-defined packages
    # Make explicit what are the dependencies we are installing
    - pip install sphinx sphinx-autorun

    # Install "sphinx-rtd-theme" from this branch because it injects the Flyout using the new documented way.
    # - pip install 'sphinx-rtd-theme @ git+https://github.com/readthedocs/sphinx_rtd_theme@humitos/flyout-menu'
    - pip install sphinx-rtd-theme

    - sphinx-build -b html docs/ _readthedocs/html

    # TODO: decide whether or not this file is required
    # - cp docs/readthedocs-build.yaml _readthedocs/html/
