version: 2

build:
  os: ubuntu-22.04
  jobs:
    post_checkout:
      - |
         echo post_checkout
         echo `date`
         git fetch --unshallow  || true
  tools:
    python: "3"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
