version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "miniconda3-4.7"
    nodejs: "16"
    rust: "1.55"
    golang: "1.17"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
