version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_install:
      - sed -i -E \"s/^     do something with multiple spaces       here    and replace it with       nothing//g\" docs/conf.py

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
