version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry using asdf
      - asdf plugin add poetry
      - asdf install poetry 1.2.0b1
      - asdf global poetry 1.2.0b1
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
      # Install project's dependencies
      - poetry install

sphinx:
  configuration: docs/conf.py
