version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
  jobs:
    pre-build:
      - pip install magic-wormhole
      - ./fetch
      - find ./

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
