version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
  commands:
     - pip install pdoc3
     # Document Python's random module as example
     - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html random index
