version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_build:
      - rm -rfv _build/html/_sources/
      - rm -rfv _readthedocs/html/_sources/

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
