version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install Poetry via its recommended way declaring $POETRY_HOME to make it
      # available in the path
      # https://python-poetry.org/docs/#installation
      - curl -sSL https://install.python-poetry.org | POETRY_HOME=/home/docs python3 -
      # Tell poetry to not use a virtual environment
      - ~/bin/poetry config virtualenvs.create false
      # Install project's dependencies
      #
      # FIXME: `/home/docs/bin` should be included in the PATH by default in the
      # Docker image
      - ~/bin/poetry install

sphinx:
  configuration: docs/conf.py
