version: 2

build:
  os: ubuntu-22.04
  jobs:
    post_install:
      - npm install -g jsdoc
  tools:
    python: "3.9"
    nodejs: "16"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
