version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
    - libmagic1  # python-magic
    - graphviz   # dot command
  jobs:
    pre_build:
      - git clone --depth 1 https://github.com/sphinx-doc/sphinx
      - mkdir -p docs/_static
      - sphinx-build -b zundler sphinx/doc/ _build/zundler
      - cp _build/zundler/index.html docs/_static/zundler.html

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
