version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
    nodejs: "latest"
    golang: "latest"
    rust: "latest"
    ruby: "latest"
  apt_packages:
    - tree
    - libasound2t64
    - jq
  jobs:
    post_checkout:
     # Test we can use a PUBLIC environment variable in a command
     - echo ${PUBLIC}

    pre_install:
      - curl 'http://devthedocs.org/api/v2/project/?slug=test-builds-disable-sphinx-manipulation' | jq
      - curl 'http://web:8000/api/v2/project/?slug=test-builds-disable-sphinx-manipulation' | jq
      - curl 'http://$READTHEDOCS_HOSTIP/api/v2/project/?slug=test-builds-disable-sphinx-manipulation' | jq
      - curl 'http://$READTHEDOCS_HOSTIP/api/v2/version/?project__slug=test-builds-disable-sphinx-manipulation&active=true' | jq

    post_install:
      # Test jsdoc
      - npm install -g jsdoc

    pre_build:
      - shot-scraper install
      - shot-scraper https://datasette.io/ --height 800 -o docs/static/datasette.png

    post_build:
      # Download a PDF sample and expose it
      - mkdir -p $READTHEDOCS_OUTPUT/pdf/
      - wget https://pdfobject.com/pdf/sample.pdf -O $READTHEDOCS_OUTPUT/pdf/my-file.pdf


sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
