version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree
    - libmagic1  # python-magic
    - graphviz   # dot command
  jobs:
    post_build:
      - mkdir --parents _readthedocs/htmlzip
      - sphinx-build -b zundler docs/ _readthedocs/htmlzip
      - mv _readthedocs/htmlzip _readthedocs/test-builds
      - mkdir _readthedocs/htmlzip
      - cd _readthedocs ; zip -r -j htmlzip/test-builds.zip test-builds
      - sphinx-build -M simplepdf docs/ _readthedocs/
      - mv _readthedocs/simplepdf/"Test Builds.pdf" _readthedocs/pdf

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
