version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
    # Force invalid version of golang to show
    # ConfigValidationError.INVALID_CHOICE notification
    golang: "3.99"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
