version: 2

build:
  os: ubuntu-22.04
  commands:
    # Creates a basic HTML
    # It should show the PR build notification, tho
    - mkdir -p _readthedocs/html/
    - mv index.html _readthedocs/html/index.html
  tools:
    python: "3"
