version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest

  jobs:
    create_environment: []
    install: []
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - echo "Hello, World!" > $READTHEDOCS_OUTPUT/html/index.html
      pdf:
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - echo "Hello, World!" > $READTHEDOCS_OUTPUT/pdf/index.pdf

python:
  install:
    - requirements: requirements.txt
