version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
    nodejs: "latest"
  apt_packages:
    - tree
  jobs:
    post_checkout:
     # Test we can use a PUBLIC environment variable in a command
     - set -x; test -n "${PUBLIC}"

    post_install:
      # Test jsdoc
      - npm install -g jsdoc

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
