version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree

# Dumb change to open a PR and test
# https://github.com/readthedocs/readthedocs-ops/pull/1402

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

