version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # Run all the commands manually to avoid installing pre-defined packages
    - env
    # Make explicit what are the dependencies we are installing
    - pip install sphinx sphinx-rtd-theme sphinx-autorun
    - sphinx-build -b html docs/ _readthedocs/html
