version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest

  jobs:
    install:
      - pip install requirements.txt
    build:
      html:
        - sphinx-build -E -b html docs/ $READTHEDOCS_OUTPUT/html
