version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3"
  jobs:
    post_build:
      # https://tectonic-typesetting.github.io/en-US/install.html
      - curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
      - python -m sphinx -T -E -j auto -b latex -d _build/doctrees -D language=en docs/ _readthedocs/latex
      - ./tectonic -X compile _readthedocs/latex/$READTHEDOCS_PROJECT.tex
      - mv $READTHEDOCS_PROJECT.pdf _readthedocs/pdf/$READTHEDOCS_PROJECT.pdf

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
