version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "latest"
  commands:
     - npm install vitepress
     - vitepress build docs
     - mkdir -p $READTHEDOCS_OUTPUT/
     - mv docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
