version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # Run all the commands manually to avoid installing pre-defined packages
    - pip install -r requirements.txt
    - sphinx-build -b html docs/ _readthedocs/html
