version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/htmlzip $READTHEDOCS_OUTPUT/pdf $READTHEDOCS_OUTPUT/epub
    - pip install -r requirements.txt
    # HTML
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
    # HTMLZip
    - sphinx-build -b zundler docs/ $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT
    - cd $READTHEDOCS_OUTPUT ; zip -r -j htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT
    # PDF
    - sphinx-build -M simplepdf docs/ $READTHEDOCS_OUTPUT/
    - mv $READTHEDOCS_OUTPUT/simplepdf/"Test Builds.pdf" $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf
    # EPUB
    - sphinx-build -b epub docs/ /tmp/epub
    - mv /tmp/epub/TestBuilds.epub $READTHEDOCS_OUTPUT/epub/$READTHEDOCS_PROJECT.epub

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
