version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install git+https://github.com/d2l-ai/d2l-book
    - cd docs ; d2lbook build html
    - mkdir -p _readthedocs/html/
    - cp --recursive docs/_build/html/* _readthedocs/html/
