version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && [ "$(git diff --quiet origin/main -- Doc/ .readthedocs.yml; echo $?)" -eq 0 ]; then \
        echo "No changes to Doc/ - exiting the build."; \
        exit 183; \
      fi
    - mkdir -p _readthedocs/html
    - echo "Hello World!" > _readthedocs/html/index.html
