version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    # Run all the commands manually to avoid installing pre-defined packages
    # Make explicit what are the dependencies we are installing
    - pip install sphinx sphinx-autorun

    # Install latest release candidate of "sphinx-rtd-theme".
    # This version injects ``data-content_root`` on the HTML tag required for search
    - pip install "sphinx-rtd-theme>=2.0.0rc4"

    - sphinx-build -b html docs/ _readthedocs/html

    # Copy data from the builder
    # This will exposed via `/_/readthedocs-config/` API endpoint
    - cp docs/readthedocs-build.yaml _readthedocs/html/
