version: 2
sphinx:
  configuration: docs/conf.py

build:
   apt_packages:
      - cmatrix
      - mysql-client
      - libgdal20

python:
   version: 3.8
   install:
   - requirements: requirements.txt
