version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      # Exit when there aren't changed in docs directory
      # --quiet exits with a 1 when there **are** changes,
      # so we invert the logic with a !
      #
      # If there are not changes (exit 0) we force the command to return with 439.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - "! git diff --quiet origin/main -- docs && exit 439"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
