version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
    nodejs: "16"
  commands:
    # Commands from https://docs.antora.org/antora/latest/install-and-run-quickstart/
    - npm i -g -D -E @antora/cli@3.1 @antora/site-generator@3.1
    - antora -v
    - antora --fetch antora-playbook.yml
    - mkdir $READTHEDOCS_OUTPUT
    - mv build/site $READTHEDOCS_OUTPUT/html
