version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - gettext
  tools:
    nodejs: "16"
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive docs/* $READTHEDOCS_OUTPUT/html/
    # Ideally, I'd like to use envsubst (part of gettext), but we can't use "build.apt_packages" with "build.commands"
    - |
      export READTHEDOCS_BUILD_DATE=`date`
      DOCTOOL_COMMIT=`git rev-parse HEAD`
      function subst() { eval echo -E "$2"; }
      mapfile -c 1 -C subst < $READTHEDOCS_OUTPUT/html/readthedocs-docsify.js
    - cat $READTHEDOCS_OUTPUT/html/readthedocs-docsify.js
