version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
    nodejs: "16"
    rust: "1.55"
    golang: "1.17"

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yaml

python:
  install:
    - requirements: requirements.txt
