version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
    nodejs: "latest"
  apt_packages:
    - tree
    - libasound2
  jobs:
    post_checkout:
     # Test we can use a PUBLIC environment variable in a command
     - echo ${PUBLIC}

    pre_build:
      - shot-scraper install
      - shot-scraper https://datasette.io/ --height 800 -o docs/static/datasette.png

    post_install:
      # Test jsdoc
      - npm install -g jsdoc


sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
