version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - mkdir --parents _readthedocs/htmlzip _readthedocs/pdf _readthedocs/epub
    - pip install -r requirements.txt
    # HTML
    - sphinx-build -b html docs/ _readthedocs/html
    # HTMLZip
    - sphinx-build -b zundler docs/ _readthedocs/$READTHEDOCS_PROJECT
    - cd _readthedocs ; zip -r -j htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT
    # PDF
    - sphinx-build -M simplepdf docs/ _readthedocs/
    - mv _readthedocs/simplepdf/"Test Builds.pdf" _readthedocs/pdf/$READTHEDOCS_PROJECT.pdf
    # EPUB
    - sphinx-build -b epub docs/ /tmp/epub
    - mv /tmp/epub/TestBuilds.epub _readthedocs/epub/$READTHEDOCS_PROJECT.epub

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
