version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3"
  jobs:
    post_install:
      - pip install git+https://github.com/readthedocs/readthedocs-sphinx-ext.git@main

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
