version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
    nodejs: latest
    ruby: latest
    rust: latest
    golang: latest
  commands:
    - python --version
    - ruby --version
    - go --version
    - node --version
    - cargo --version
