site_name: readthedocs
site_description: A build to test MkDocs with PDF
copyright: "2022"

nav:
  - Overview: "index.md"

plugins:
  - with-pdf:
      # TODO: find a way to use $READTHEDOCS_OUTPUT and $READTHEDOCS_PROJECT
      # output_path: $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT.pdf
      output_path: ../pdf/test-builds.pdf
